routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Routing\RouteGroup;

Route::group(["prefix"=>"comprehensive/admin", "as"=>"main."], function(){

    Route::group(["middleware" => "auth"], function () {
        Route::get('/dashboard', 'HomeController@dashboard')->name("dashboard");

        Route::group(['prefix' => 'doctors'], function () {
            Route::get('/', 'doctorsController@index')->name('doctors');
            Route::match(["GET", "POST"], '/post/{id?}', 'doctorsController@post')->name('doctors-post');
        });

        Route::group(['prefix' => 'offers', "as"=>"offer."], function () {
            Route::get('/', 'offerController@index')->name('index');
            Route::match(["GET", "POST"], '/post/{id?}', 'offerController@offerPost')->name('post');
        });

        Route::get('contact-us', 'contactUsController@index')->name('contact-us');
        Route::post('/contact-us-post', 'contactUsController@contactUsPost')->name('contact-us-post');
    });

    Auth::routes();

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Routing\RouteGroup;

Route::get('/', 'ComprehensiveController@index')->name('home');
Route::get('about', 'ComprehensiveController@aboutus')->name('about');
Route::get('mission-vision', 'ComprehensiveController@missionvisionvalues')->name('mission&vision');
Route::get('services', 'ComprehensiveController@servicesshow')->name('services');
Route::get('contactus', 'ComprehensiveController@contactusshow')->name('contactus');
Route::post('contactcomprehensive', 'ComprehensiveController@contactcomprehensivesubmit')->name('contactcomprehensive');
Route::post('Comprehensiveappointment', 'ComprehensiveController@Comprehensiveappointmentnow')->name('Comprehensiveappointment');
Route::get('doctors', 'ComprehensiveController@doctorsshow')->name('doctors');

resources/views/admin/includes/footer.blade.php
	<!-- page-content" -->
	<div class="clearfix"></div>
</div>
<!-- page-wrapper -->
<!-- Jquery Link -->
<script src="{{ asset("assets/plugins/jquery-3.3.1/jquery.min.js") }}"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="{{ asset("assets/js/bootstrap.min.js") }}"></script>
<!-- Readmore.js-master -->
<script src="{{ asset("assets/plugins/Readmore.js-master/readmore.js") }}"></script>

<!-- Datatable -->
<script src="{{ asset("assets/plugins/DataTables/datatables.min.js") }}"></script>

<!-- Datatable Buttons -->
{{-- <script src="{{ asset("assets/plugins/DataTables/Buttons-1.4.2/js/dataTables.buttons.min.js") }}"></script>
<script src="{{ asset("assets/plugins/DataTables/Buttons-1.4.2/js/buttons.html5.min.js") }}"></script>
<script src="{{ asset("assets/plugins/DataTables/Buttons-1.4.2/js/buttons.print.min.js") }}"></script>
<script src="{{ asset("assets/plugins/DataTables/Buttons-1.4.2/js/buttons.flash.min.js") }}"></script>
<script src="{{ asset("assets/plugins/DataTables/Buttons-1.4.2/js/buttons.colVis.min.js") }}"></script>
<script src="{{ asset("assets/plugins/DataTables/pdfmake-0.1.32/pdfmake.min.js") }}"></script>
<script src="{{ asset("assets/plugins/DataTables/pdfmake-0.1.32/vfs_fonts.js") }}"></script>
<script src="{{ asset("assets/plugins/DataTables/JSZip-2.5.0/jszip.min.js") }}"></script> --}}

<!-- Select2  -->
<script type="text/javascript" src="{{ asset("assets/plugins/select2/dist/js/select2.full.min.js") }}"></script>

{{-- Jquery Validaton --}}
<script type="text/javascript" src="{{ asset("assets/plugins/jquery-validation-master/jquery.validate.min.js") }}"></script>

{{-- DateRangePicker --}}
<script src="{{ asset("assets/plugins/daterangepicker-master/moment.min.js") }}"></script>
<script src="{{ asset("assets/plugins/daterangepicker-master/daterangepicker.js") }}"></script>

{{-- Sweet Alert --}}
<link rel="stylesheet" href="{{ asset('assets/plugins/sweetalert2-master/sweetalert2.min.css') }}">
<script src="{{ asset('assets/plugins/sweetalert2-master/sweetalert2.all.min.js') }}"></script>
<script src="{{ asset('assets/plugins/jquery-validation-master/jquery.validate.min.js') }}"></script>

@if($msg = Session::get('msg'))
	@php
		if($msg[0] == "success"){
			$title = "Good Job!";
		}else if($msg[0] == "error"){
			$title = "Error!";
		}
	@endphp
@endif

<script>

    $.validator.setDefaults({
        errorElement: 'label',
        errorClass: 'error',
        errorPlacement: function (error, element) {
            if (element.parents('.input-group').length) {
                error.insertAfter(element.parents('.input-group'));
            } else if (element.data('select2')) {
                if(element.parent().hasClass("form-group")){
                    element.parent('.form-group').append(error);
                }else if(element.parent('div')){
                    element.parent('div').append(error);
                }
            }else{
                error.insertAfter(element);
            }
        }
    });

	$(document).ready(function() {
		$("body").removeClass("preload");
	});

	@if($msg = Session::get('msg'))
		Swal.fire(
			"{{ $title }}",
			"{{ $msg[1] }}",
			"{{ $msg[0] }}"
		)
	@endif

	currentURL = '{{ url()->full() }}';

	$.fn.SidebarActive = function($value){
		$('.tadbeer-theme .sidebar-wrapper .sidebar-menu ul li a').each(function(){
			if($(this).attr('href') == $value){
				if($(this).parents().hasClass('sidebar-dropdown')){
					$(this).closest('.sidebar-dropdown').addClass('active');
					$(this).parent('li').addClass('active')
					$(this).closest('.sidebar-dropdown').find('.sidebar-submenu').show();
				}else{
					$(this).parent('li').addClass('active')
				}
			}
		});
	}

	$.fn.SidebarActive(currentURL);
    $.each($('form'), function(ii, ele) {
        $(ele).attr('autocomplete', 'off');
    })
</script>

<script src="{{ asset('assets/js/custom.js') }}"></script>
@stack('footer-js')
</body>
</html>

resources/views/admin/includes/header.blade.php
<!DOCTYPE html>
<html>
	<head>
		<title>Comprehensive Diabetes Center | @yield('title') </title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
		{{-- <link rel="shortcut icon" type="image/png" href="{{ asset("assets/img/icons/fav-icon.png") }}"/> --}}
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="{{ asset("assets/css/bootstrap.min.css") }}">
		<!-- Optional theme -->
		<link rel="stylesheet" href="{{ asset("assets/css/bootstrap-theme.min.css") }}">
		<link rel="stylesheet" href="{{ asset("assets/css/theme-style.min.css") }}">
		<link rel="stylesheet" href="{{ asset("assets/css/style.min.css") }}">
		<link rel="stylesheet" href="{{ asset("assets/css/responsive.min.css") }}">
		<!-- Font Awesome 5 -->
		<link href="{{ asset("assets/plugins/fontawesome-5.8.1/css/all.css") }}" rel="stylesheet">

		<!-- DataTables -->
		<link rel="stylesheet" href="{{ asset("assets/plugins/DataTables/datatables.min.css") }}">

		<!-- Open+Sans font-->
		<link href="{{ asset("assets/fonts/custom-font.css") }}" rel="stylesheet">
		<!-- Select 2 -->
		<link href="{{ asset("assets/plugins/select2/dist/css/select2.min.css") }}" rel="stylesheet">

	</head>
	<body class="preload">
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container-fluid">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					</div><!-- /.navbar-collapse -->
					</div><!-- /.container-fluid -->
				</nav>
				<div class="page-wrapper tadbeer-theme toggled">
					<a id="show-sidebar" class="btn btn-sm btn-dark">
						<i class="fas fa-bars"></i>
					</a>
					<nav id="sidebar" class="sidebar-wrapper">
						<div class="sidebar-content">
							<div class="sidebar-brand">
								<a href="{{ route("main.dashboard") }}">
									<h1>Comprehensive Diabetes Center</h1>
								</a>
								<div id="close-sidebar">
									<i class="fas fa-toggle-on"></i>
								</div>
							</div>
							<div class="sidebar-header">
								<div class="user-pic">
									<img class="img-responsive img-rounded" src="{{ asset("assets/img/icons/avatar-male.jpg") }}" alt="User picture">
								</div>
								<div class="user-info">
									<span class="user-name">{{ Auth::user()->name }}
									</span>
									<span class="user-role">Administrator</span>
									<span class="user-status">
										<i class="fa fa-circle"></i>
										<span>Online</span>
									</span>
								</div>
							</div>
                            @include('admin.includes.notifications')
							<!-- sidebar-search  -->
							<div class="sidebar-menu">
								<ul>
									<li class="header-menu">
										<span>General</span>
									</li>
									<li>
										<a href="{{ route("main.dashboard") }}">
											<i class="fa fa-tachometer-alt"></i>
											<span>Dashboard</span>
										</a>
									</li>
									<li class="header-menu">
										<span>Others</span>
									</li>
									<li>
										<a href="{{ route('main.contact-us') }}">
											<i class="fa fa-phone"></i>
											<span>Update Contact Us</span>
										</a>
									</li>
									<li>
										<a href="{{ route('main.doctors') }}">
											<i class="fa fa-users"></i>
											<span>Doctors</span>
										</a>
									</li>
                                    <li>
                                        <a href="{{ route('main.offer.index') }}">
											<i class="fa fa-bell"></i>
											<span>Offers</span>
										</a>
									</li>
								</ul>
							</div>
						</div>
					</nav>

resources/views/admin/includes/notifications.blade.php
<!-- Notification-content  -->
<div class="sidebar-footer">
    <a href="#">
        <i class="fa fa-bell"></i>
        <!-- <span class="badge badge-pill badge-warning notification">3</span> -->
    </a>
    <a href="#">
        <i class="fa fa-envelope"></i>
        <!-- <span class="badge badge-pill badge-success notification">7</span> -->
    </a>
    <a href="">
        <i class="fa fa-cog"></i>
        <span class="badge-sonar"></span>
    </a>
    <a href="{{ route('main.logout') }}"
    onclick="event.preventDefault();
                  document.getElementById('logout-form').submit();">
        <i class="fa fa-power-off"></i>
    </a>
    <form id="logout-form" action="{{ route('main.logout') }}" method="POST" style="display: none;">
        @csrf
    </form>
</div>